# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      -
        name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
          channel: 'stable'
      -
        name: Build Flutter Web
        run: |
          flutter pub get
          flutter config --enable-web
          flutter build web
          cp build/web docker/web
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: blueloveth
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push Docker Image
        run: |
          cd docker
          export image_tag=registry.cn-shenzhen.aliyuncs.com/codemart/palette:latest
          docker build -t $image_tag .
          docker push $image_tag
    
